apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    DB_PASSWORD: "mypassword"
    KEYCLOAK_ADMIN: "pedro1234"
    KEYCLOAK_ADMIN_PASSWORD: "guanabana555"
    KC_CLIENT_SECRET: "secreto-api-123"
    KC_USER_PASSWORD: "12345"